version: '2.4'

services:

  nodejs:
    image: my-nodejs-image 
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
  
  nginx:
    image: nginx
    ports:
      - "80:80" 
    volumes:
      - ./node-nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
